apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  labels:
    app: {{ include "my-postgres-chart.name" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: postgresql
      protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: 5432
  selector:
    app: {{ include "my-postgres-chart.name" }}
