apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: userservice-monitor
  labels:
    release: prometheus-stack
spec:
  selector:
    matchLabels:
      app: userservice
  endpoints:
    - port: http
      path: /actuator/prometheus
      interval: 15s