apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-appuser
spec:
  ingressClassName: nginx
  rules:
    - host: arch.homework # Общий хост
      http:
        paths:
          # Маршрут для user-service
          - path: /api/user(/|$)(.*)  # Новый префикс!
            pathType: Prefix
            backend:
              service:
                name: service-appuser  # Kubernetes Service для user-service
                port:
                  number: 80

          # Маршрут для auth-service
          - path: /api/auth(/|$)(.*)   # Префикс для auth-service
            pathType: Prefix
            backend:
              service:
                name: auth-service  # Имя Service для auth-service
                port:
                  number: 80